// WARNING: This file is auto-generated by a script.
// Any changes made to this file may be overwritten.
// Please modify the code generation script instead.
// Path to the code generation script: scripts/gen_c_api.py

#pragma once
#ifndef PALLAS_API_H
#define PALLAS_API_H

#include <cuda_runtime.h>
#include "gpu-utils/device_context.cuh"
#include "curves/params/pallas.cuh"
#include "ntt/ntt.cuh"
#include "msm/msm.cuh"
#include "vec_ops/vec_ops.cuh"

extern "C" cudaError_t pallas_ecntt_cuda(
  const pallas::projective_t* input, int size, ntt::NTTDir dir, ntt::NTTConfig<pallas::scalar_t>& config, pallas::projective_t* output);

extern "C" cudaError_t pallas_precompute_msm_bases_cuda(
  pallas::affine_t* bases,
  int bases_size,
  int precompute_factor,
  int _c,
  bool are_bases_on_device,
  device_context::DeviceContext& ctx,
  pallas::affine_t* output_bases);

extern "C" cudaError_t pallas_msm_cuda(
  const pallas::scalar_t* scalars, const pallas::affine_t* points, int msm_size, msm::MSMConfig& config, pallas::projective_t* out);

extern "C" bool pallas_eq(pallas::projective_t* point1, pallas::projective_t* point2);

extern "C" void pallas_to_affine(pallas::projective_t* point, pallas::affine_t* point_out);

extern "C" void pallas_generate_projective_points(pallas::projective_t* points, int size);

extern "C" void pallas_generate_affine_points(pallas::affine_t* points, int size);

extern "C" cudaError_t pallas_affine_convert_montgomery(
  pallas::affine_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t pallas_projective_convert_montgomery(
  pallas::projective_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t pallas_mul_cuda(
  pallas::scalar_t* vec_a, pallas::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, pallas::scalar_t* result);

extern "C" cudaError_t pallas_add_cuda(
  pallas::scalar_t* vec_a, pallas::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, pallas::scalar_t* result);

extern "C" cudaError_t pallas_sub_cuda(
  pallas::scalar_t* vec_a, pallas::scalar_t* vec_b, int n, vec_ops::VecOpsConfig& config, pallas::scalar_t* result);

extern "C" cudaError_t pallas_transpose_matrix_cuda(
  const pallas::scalar_t* input,
  uint32_t row_size,
  uint32_t column_size,
  pallas::scalar_t* output,
  device_context::DeviceContext& ctx,
  bool on_device,
  bool is_async);

extern "C" void pallas_generate_scalars(pallas::scalar_t* scalars, int size);

extern "C" cudaError_t pallas_scalar_convert_montgomery(
  pallas::scalar_t* d_inout, size_t n, bool is_into, device_context::DeviceContext& ctx);

extern "C" cudaError_t pallas_initialize_domain(
  pallas::scalar_t* primitive_root, device_context::DeviceContext& ctx, bool fast_twiddles_mode);

extern "C" cudaError_t pallas_ntt_cuda(
  const pallas::scalar_t* input, int size, ntt::NTTDir dir, ntt::NTTConfig<pallas::scalar_t>& config, pallas::scalar_t* output);

extern "C" cudaError_t pallas_release_domain(device_context::DeviceContext& ctx);

#endif